version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - run:
          name: Install Dependencies
          command: sudo apt update; sudo apt install -y cmake build-essential
      - checkout
      - run:
          name: Checkout Submodules
          command: git submodule init; git submodule update
      - run:
          name: Build
          command: mkdir build; cd build; cmake ..; make
